  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module color_object::color_object_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::dapps_system;

  use dubhe::storage_migrate;

  use dubhe::dapps_schema::Dapps;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use color_object::dapp_key::DappKey;

  use sui::dynamic_field as df;

  public struct ColorObject has key, store {
    id: UID,
  }

  public fun borrow_red(self: &ColorObject): &StorageValue<u8> {
    storage_migrate::borrow_field(&self.id, b"red")
  }

  public(package) fun borrow_mut_red(self: &mut ColorObject): &mut StorageValue<u8> {
    storage_migrate::borrow_mut_field(&mut self.id, b"red")
  }

  public fun borrow_green(self: &ColorObject): &StorageValue<u8> {
    storage_migrate::borrow_field(&self.id, b"green")
  }

  public(package) fun borrow_mut_green(self: &mut ColorObject): &mut StorageValue<u8> {
    storage_migrate::borrow_mut_field(&mut self.id, b"green")
  }

  public fun borrow_blue(self: &ColorObject): &StorageValue<u8> {
    storage_migrate::borrow_field(&self.id, b"blue")
  }

  public(package) fun borrow_mut_blue(self: &mut ColorObject): &mut StorageValue<u8> {
    storage_migrate::borrow_mut_field(&mut self.id, b"blue")
  }

  public(package) fun create(ctx: &mut TxContext): ColorObject {
    let mut id = object::new(ctx);
    storage_migrate::add_field<StorageValue<u8>>(&mut id, b"red", storage_value::new());
    storage_migrate::add_field<StorageValue<u8>>(&mut id, b"green", storage_value::new());
    storage_migrate::add_field<StorageValue<u8>>(&mut id, b"blue", storage_value::new());
    ColorObject { id }
  }

  public fun migrate(_color_object: &mut ColorObject, _cap: &UpgradeCap) {}

  // ======================================== View Functions ========================================

  public fun get_red(self: &ColorObject): Option<u8> {
    self.borrow_red().try_get()
  }

  public fun get_green(self: &ColorObject): Option<u8> {
    self.borrow_green().try_get()
  }

  public fun get_blue(self: &ColorObject): Option<u8> {
    self.borrow_blue().try_get()
  }

  // =========================================================================================================
}
